## Comment for testing workflow
name: main_pipeline
on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '6.0'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Microservice
        run: |
          # build your application here
          echo "Building application..."
          dotnet build --configuration Release
  
      - name: Test Microservice
        run: dotnet test



  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          # install any dependencies needed for testing
          echo "Installing dependencies..."
          sleep 15

      - name: Run tests
        run: |
          # run your tests here
          echo "Running tests..."
          sleep 15

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy application
        run: |
          # deploy your application here
          echo "Deploying application..."
          sleep 15
